GET http://localhost:5266/api/chatroom

GET http://localhost:5266/api/chatroom?userId=1&roomType=1


GET http://localhost:5266/api/chatroom/1

GET http://localhost:5266/api/chatroom?userId=2&roomType=1&hasjoin=false



POST http://localhost:5266/api/chatroom
Content-Type: application/json

{
    "Roomname": "testRoom3",
    "CreatedByUserId": 1,
    "RoomType": 1
}

POST http://localhost:5266/api/chatroom/1/join
Content-Type: application/json

{
    "UserId": 2
}

POST http://localhost:5266/api/chatroom/1/kick
Content-Type: application/json

{
    "RequestUserId": 3,
    "KickUserId":2
}


PATCH  http://localhost:5266/api/chatroom/1
Content-Type: application/json

{
    "Roomname":"testRoom2-2"
}


DELETE  http://localhost:5266/api/chatroom/3


DELETE  http://localhost:5266/api/chatroom/1/leave
Content-Type: application/json

{
    "UserId": 2
}